/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DummyInfoPanel.java
 *
 * Created on 13 sept. 2011, 17:09:30
 */

package aurelienribon.leveleditor.ui.infopanels;

import aurelienribon.leveleditor.ui.Theme;

/**
 *
 * @author Aurelien Ribon | http://www.aurelienribon.com
 */
public class SpritesModeInfoPanel extends javax.swing.JPanel {

    /** Creates new form DummyInfoPanel */
    public SpritesModeInfoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(Theme.MAIN_ALT_BACKGROUND);

        jLabel1.setForeground(Theme.MAIN_ALT_FOREGROUND);
        jLabel1.setText("<html>\n<b>Help:</b> Change the asset with &lt;TAB&gt; or &lt;shift&gt;+&lt;TAB&gt;, and click on the screen to place it.\nYou can move/resize/rotate it later with the SELECT tool.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
